/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mymailer.view;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author medkh
 */
public class MainView extends javax.swing.JFrame {

    // JPanel central pour accueillir d'autres vues
    private JPanel mainPanel;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        initCustomLayout();
    }
    
    private void initCustomLayout() {
        setTitle("MyMailer - Main View");
        setLocationRelativeTo(null);
        setSize(700, 500);

        // Initialisation du mainPanel en tant que conteneur central
        mainPanel = new JPanel(new BorderLayout());

        // Ajout du mainPanel au centre du JFrame
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(mainPanel, BorderLayout.CENTER);
    }
    
    // Méthode pour changer dynamiquement la vue affichée
    public void setView(JPanel view) {
        mainPanel.removeAll();            // supprime la vue actuelle
        mainPanel.add(view, BorderLayout.CENTER); // ajoute la nouvelle vue
        mainPanel.revalidate();           // revalide le layout
        mainPanel.repaint();              // force la mise à jour visuelle
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
